### ISSUE TITLE
Application looks for App\bins\bin.exe - Which is not present

### ISSUE THREAD

**Issue by Isaiahfeldt** [rossepsteini/Auto-Hacking-USB#1]
Running the start.bat will try to look up App\bins\bin.exe, even though it's not in the github or downloadable zip file.

**Comment by rossepsteini** [comment]
In the next update I will be adding a file that will automatically rename your virus in the bins folder to bin.exe and then remove itself. Right now AHU offers the ability to spread your own virus using the program, but you must manually rename and add the file. This is what it is looking for. In the next update if the bin.exe file isn't present it will remove the line to search for the program in start.bat.
